### ISSUE TITLE
task ansible-role-cvmfs is failing

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-cvmfs#2]
when running grid.yml if fgci-ansible.

Apparently the template doesn't use  ansible_hostname variable so I guess this error message might be a bit misleading.

Output:

TASK: [ansible-role-cvmfs | template cvmfs/default.local if none exists] *****\* 
fatal: [io-grid.fgci.csc.fi] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_hostname'", 'failed': True}
fatal: [io-grid.fgci.csc.fi] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_hostname'", 'failed': True}

**Comment by martbhell** [comment]
"ansible-playbook -u MYUSER -i hosts grid.yml --tags cvmfs" works for me - is it still broken for you?

**Comment by martbhell** [comment]
This role works fine for us now during our cluster reinstall exercises.
